spring:
  application:
    name: OpenApi
  datasource:
    url: { POSTGRES_DB_URL }
    username: { POSTGRES_DB_USERNAME }
    password: { POSTGRES_DB_PASSWORD }
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true